export const dishes = [
{
    id: 1,
    name: "Juha od rajčica",
    price: 1,
    category: "juha",
    image: "https://placehold.co/400x250?text=juha+od+rajčice",
    url:"https://en.wikipedia.org/wiki/Juha",
},
{
    id: 3,
    name: "Tjestenina bolonjez",
    price: 3,
    category: "glavno jelo",
    image: "https://placehold.co/400x250?text=tjestenina+bolonjez",
    url:"https://en.wikipedia.org/wiki/Tjestenina",
},
{
    id: 3,
    name: "Ćevapi s lepinjom",
    price: 4,
    category: "glavno jelo",
    image: "https://placehold.co/400x250?text=ćevapi+s+lepinjom",
    url:"https://en.wikipedia.org/wiki/Ćevapi",
},
{
    id: 4,
    name: "Grah s kobasicama",
    price: 2,
    category: "glavno jelo",
    image: "https://placehold.co/400x250?text=grah+s+kobasicama",
    url:"https://en.wikipedia.org/wiki/Grah",
},
{
    id: 5,
    name: "Pečena piletina",
    price: 4,
    category: "glavno jelo",
    image: "https://placehold.co/400x250?text=pečena+piletina",
    url:"https://en.wikipedia.org/wiki/Piletina",
},
{
    id: 6,
    name: "Palačinke",
    price: 2,
    category: "desert",
    image: "https://placehold.co/400x250?text=palačinke",
    url:"https://en.wikipedia.org/wiki/Palačinke",
},
];